repos:
  # Black - Code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^venv/

  # Autoflake - Remove unused imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1  # или актуальная версия
    hooks:
      - id: autoflake
        args: [--in-place, --remove-unused-variables, --remove-all-unused-imports]
        exclude: ^venv/
